version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    container_name: postgres_db
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../IntegralData/database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  backend:
    container_name: backend
    image: jobprojects/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - MINIO_ENDPOINT=http://minio:9000
      # - MINIO_ENDPOINT=http://localhost:9095
    volumes:
      - ./backend:/app
      - ../IntegralData/staticfiles:/app/data/staticfiles
      - ../IntegralData/mediafiles:/app/data/mediafiles
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio_datalake
    ports:
      - '9095:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
      - ../IntegralData/datalake:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

volumes:
  postgres_data:
  minio_data:
